# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-16 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('tel_user_phone', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=255)),
                ('user_comment', models.TextField(blank=True)),
                ('hotel', models.CharField(choices=[('Алмаз-Плюс', 'Алмаз'), ('Алмаз-Плюс', 'Алмаз-Плюс')], max_length=100)),
                ('room_class', models.CharField(choices=[('Стандарт', 'Стандарт'), ('Напівлюкс', 'Напівлюкс'), ('Люкс', 'Люкс')], max_length=100)),
                ('date_entry', models.DateField()),
                ('date_out', models.DateField()),
                ('number_of_people', models.IntegerField()),
                ('time', models.TimeField(auto_now=True)),
            ],
            options={
                'db_table': 'book_room',
            },
        ),
        migrations.CreateModel(
            name='BookingTourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('tel_user_phone', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=255)),
                ('user_comment', models.TextField(blank=True)),
                ('tour_name', models.CharField(choices=[('Полтава історична', 'Полтава історична'), ('Етнографічний маршрут “Білим по білому”', 'Етнографічний маршрут “Білим по білому”'), ('Історичне Поле Полтавської битви', 'Історичне Поле Полтавської битви'), ('Літературна Полтава', 'Літературна Полтава'), ('Диканька. Подорож на батьківщину Рудого Панька', 'Диканька. Подорож на батьківщину Рудого Панька'), ('Гоголем оспівана земля!', 'Гоголем оспівана земля!'), ('Історико-культурна спадщина монастирів Полтавщини', 'Історико-культурна спадщина монастирів Полтавщини'), ('Храми Полтави', 'Храми Полтави'), ('Дорогами Сковороди', 'Дорогами Сковороди'), ('Опішне – гончарна столиця України', 'Опішне – гончарна столиця України'), ('Більське городище', 'Більське городище'), ('Миргород. Подорож до королеви мінеральних вод', 'Миргород. Подорож до королеви мінеральних вод')], max_length=100)),
                ('date_entry', models.DateField()),
                ('number_of_people', models.IntegerField()),
                ('time', models.TimeField(auto_now=True)),
            ],
            options={
                'db_table': 'book_tour',
            },
        ),
    ]
