# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-16 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20180116_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='date_entry',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='date_out',
            field=models.CharField(max_length=30),
        ),
    ]
