# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-16 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20180116_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtourmodel',
            name='date_entry',
            field=models.CharField(max_length=30),
        ),
    ]
