# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-16 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20180116_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='username',
            field=models.CharField(max_length=50, verbose_name='ПІБ'),
        ),
    ]
