# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-16 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20180116_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingmodel',
            options={'verbose_name': 'Бронювання готелю'},
        ),
        migrations.AlterModelOptions(
            name='bookingtourmodel',
            options={'verbose_name': 'Бронювання туру'},
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='date_entry',
            field=models.CharField(max_length=30, verbose_name='Дата заїзду'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='date_out',
            field=models.CharField(max_length=30, verbose_name='Дата виїзду'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='hotel',
            field=models.CharField(choices=[('Алмаз-Плюс', 'Алмаз'), ('Алмаз-Плюс', 'Алмаз-Плюс')], max_length=100, verbose_name='Назва Готелю'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='number_of_people',
            field=models.IntegerField(verbose_name='Кількість людей'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='room_class',
            field=models.CharField(choices=[('Стандарт', 'Стандарт'), ('Напівлюкс', 'Напівлюкс'), ('Люкс', 'Люкс')], max_length=100, verbose_name='Клас кімнати'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='tel_user_phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='Час бронювання'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='user_comment',
            field=models.TextField(blank=True, verbose_name='Додатковий коментар'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='user_email',
            field=models.EmailField(max_length=255, verbose_name='Пошта'),
        ),
        migrations.AlterField(
            model_name='bookingtourmodel',
            name='date_entry',
            field=models.CharField(max_length=30, verbose_name='Дата виїзду'),
        ),
        migrations.AlterField(
            model_name='bookingtourmodel',
            name='number_of_people',
            field=models.IntegerField(verbose_name='Кількість людей'),
        ),
        migrations.AlterField(
            model_name='bookingtourmodel',
            name='tel_user_phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='bookingtourmodel',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='Час бронювання'),
        ),
        migrations.AlterField(
            model_name='bookingtourmodel',
            name='tour_name',
            field=models.CharField(choices=[('Полтава історична', 'Полтава історична'), ('Етнографічний маршрут “Білим по білому”', 'Етнографічний маршрут “Білим по білому”'), ('Історичне Поле Полтавської битви', 'Історичне Поле Полтавської битви'), ('Літературна Полтава', 'Літературна Полтава'), ('Диканька. Подорож на батьківщину Рудого Панька', 'Диканька. Подорож на батьківщину Рудого Панька'), ('Гоголем оспівана земля!', 'Гоголем оспівана земля!'), ('Історико-культурна спадщина монастирів Полтавщини', 'Історико-культурна спадщина монастирів Полтавщини'), ('Храми Полтави', 'Храми Полтави'), ('Дорогами Сковороди', 'Дорогами Сковороди'), ('Опішне – гончарна столиця України', 'Опішне – гончарна столиця України'), ('Більське городище', 'Більське городище'), ('Миргород. Подорож до королеви мінеральних вод', 'Миргород. Подорож до королеви мінеральних вод')], max_length=100, verbose_name='Назва Туру'),
        ),
        migrations.AlterField(
            model_name='bookingtourmodel',
            name='user_comment',
            field=models.TextField(blank=True, verbose_name='Додатковий коментар'),
        ),
        migrations.AlterField(
            model_name='bookingtourmodel',
            name='user_email',
            field=models.EmailField(max_length=255, verbose_name='Пошта'),
        ),
        migrations.AlterField(
            model_name='bookingtourmodel',
            name='username',
            field=models.CharField(max_length=50, verbose_name='ПІБ'),
        ),
    ]
