# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-19 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20180116_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='room_class',
            field=models.CharField(choices=[('Стандарт', 'Стандарт'), ('Напівлюкс', 'Напівлюкс'), ('Люкс', 'Люкс'), ('Ліжкомісце', 'Ліжкомісце')], max_length=100, verbose_name='Клас кімнати'),
        ),
    ]
