# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-27 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20180119_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='hotel',
            field=models.CharField(choices=[('Алмаз', 'Алмаз'), ('Алмаз-плюс', 'Алмаз-плюс')], max_length=100, verbose_name='Назва Готелю'),
        ),
    ]
