# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-16 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to='%Y/%m/%d')),
                ('title_uk', models.CharField(max_length=200, verbose_name='Title (uk)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (en)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Title (ru)')),
                ('text_uk', models.TextField(blank=True, verbose_name='Text (uk)')),
                ('text_en', models.TextField(blank=True, verbose_name='Text (en)')),
                ('text_ru', models.TextField(blank=True, verbose_name='Text (ru)')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
