# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-19 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_albumimage_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(default='New', max_length=1024),
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.CharField(default='new', max_length=250),
        ),
        migrations.AddField(
            model_name='album',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='albums'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albumimage',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='albums'),
            preserve_default=False,
        ),
    ]
