# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-19 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20180119_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='description',
        ),
        migrations.RemoveField(
            model_name='album',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='album',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='thumb',
        ),
    ]
