# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-16 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name_uk', models.CharField(max_length=70)),
                ('page_name_en', models.CharField(max_length=70)),
                ('page_name_ru', models.CharField(max_length=70)),
                ('seo_title_uk', models.CharField(max_length=170)),
                ('seo_title_en', models.CharField(max_length=170)),
                ('seo_title_ru', models.CharField(max_length=170)),
                ('seo_description_uk', models.TextField()),
                ('seo_description_en', models.TextField()),
                ('seo_description_ru', models.TextField()),
                ('seo_keywords_uk', models.TextField()),
                ('seo_keywords_en', models.TextField()),
                ('seo_keywords_ru', models.TextField()),
            ],
            options={
                'db_table': 'seo',
            },
        ),
    ]
